// <auto-generated />
using System;
using EasyPoker_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyPoker_API.Migrations
{
    [DbContext(typeof(EasyPokerContext))]
    partial class EasyPokerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyPoker_API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Games__3214EC073CB3E97B");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EasyPoker_API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Players__3214EC07C4E2E9F4");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EasyPoker_API.Models.PlayerHand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Card1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Card2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Card3")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Card4")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Card5")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PlayerHa__3214EC07A148B41B");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerHands");
                });

            modelBuilder.Entity("EasyPoker_API.Models.RemainingCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Remainin__3214EC079F8CAE2F");

                    b.HasIndex("GameId");

                    b.ToTable("RemainingCards");
                });

            modelBuilder.Entity("EasyPoker_API.Models.Player", b =>
                {
                    b.HasOne("EasyPoker_API.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Players__GameId__3A81B327");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("EasyPoker_API.Models.PlayerHand", b =>
                {
                    b.HasOne("EasyPoker_API.Models.Game", "Game")
                        .WithMany("PlayerHands")
                        .HasForeignKey("GameId")
                        .HasConstraintName("FK__PlayerHan__GameI__412EB0B6");

                    b.HasOne("EasyPoker_API.Models.Player", "Player")
                        .WithMany("PlayerHands")
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK__PlayerHan__Playe__4222D4EF");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("EasyPoker_API.Models.RemainingCard", b =>
                {
                    b.HasOne("EasyPoker_API.Models.Game", "Game")
                        .WithMany("RemainingCards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Remaining__GameI__4F7CD00D");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("EasyPoker_API.Models.Game", b =>
                {
                    b.Navigation("PlayerHands");

                    b.Navigation("Players");

                    b.Navigation("RemainingCards");
                });

            modelBuilder.Entity("EasyPoker_API.Models.Player", b =>
                {
                    b.Navigation("PlayerHands");
                });
#pragma warning restore 612, 618
        }
    }
}
